name:                mgs
version:             0.0.0.1
github:              pniedzielski/mgs
license:             LGPL-3.0-or-later
license-file:        [ COPYING.LGPL.md, COPYING.GPL.md ]
author:              Patrick M. Niedzielski
maintainer:          Patrick M. Niedzielski <patrick@pniedzielski.net>
copyright:           Copyright (C) 2020, Patrick M. Niedzielski.
synopsis:            Tools for working with Minimalist Grammars
category:            Text
description:         >-
  This package contains parsers and other utilities for working with
  Minimalist Grammars (MGs) and related formalisms.  The goal for this
  package is to provide a high-quality, well-documented playground for
  understanding MGs.

extra-source-files:
  - README.md
  - COPYING.GPL.md
  - COPYING.LGPL.md
  - package.yaml

ghc-options: -Wall -O3
default-extensions:
  - UnicodeSyntax

library:
  source-dirs: library
  dependencies:
    - base
    - base-unicode-symbols
    - compdata
    - containers
    - hashmap
    - ixset
    - megaparsec
    - monad-loops
    - more-containers
    - parser-combinators
    - text
    - tree-view
    - vector

executables:
  mgs:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - base-unicode-symbols
      - mgs
      - compdata
      - containers
      - megaparsec
      - text
      - tree-view
    ghc-options:
      -rtsopts
      -threaded
      -with-rtsopts=-N

tests:
  mgs-test-suite:
    source-dirs: tests
    main: Main.hs
    dependencies:
    - base
    - base-unicode-symbols
    - mgs
    - HUnit
    - tasty
    - tasty-hunit
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
